[package]
name = "k3-sdhci"
version = "0.1.0"
repository.workspace = true
edition = "2024"
license = "Apache-2.0"
description = "SpacemiT K3 SDHCI host controller driver (no_std)"
keywords = ["spacemit", "k3", "sdhci", "embedded", "no_std"]
categories = ["embedded", "no-std", "hardware-support"]

[dependencies]
log.workspace = true
mmio-api.workspace = true
bitflags = "2"
thiserror.workspace = true
